### ISSUE TITLE
Regarding contributions

### ISSUE THREAD

**Issue by razilsh** [worker8/Pixels#26]
Hello, @worker8 Very cool project. Do you have any guidelines for people who would like to contribute?

**Comment by worker8** [comment]
thanks @razilsh !

I actually haven't thought about contribution yet, since I just started the project out of interest.

I haven't write a general guideline, but I think that it would be roughly like this:

- for architectural change or new features, opening up a new feature to discuss first would be good
- for making smaller change or fix, opening a pull request directly should be fine
- try to use the same pattern as the existing code so that it's easier to maintain

I also haven't think of the future features of what it's going to be. So feel free to play around with the project.

Anyhow thanks for your interest! 😀

**Comment by razilsh** [comment]
> I actually haven't thought about contribution yet, since I just started the project out of interest.

Yep, that's exactly why I asked \^\_\^\. And your points make complete sense. Maybe we could start by adding a `CONTRIBUTING.md`? I could send a PR if you're okay with that ^_^

**Comment by worker8** [comment]
sure~ I will review it 😄
